### ISSUE TITLE
Add documentation for Part3_Classification

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/Machine-Learning-with-Python#1]
Currently, there is no explanation for concepts of classification in ML.
It would be nice if all types of classification can be briefly explained (similar to part1 and part2 concepts)

**Comment by abhinand5** [comment]
I can do that. Can you assign me?

**Comment by Vishruth-S** [comment]
Sure @abhinand5  Go ahead

**Comment by ArjunBhandari-666** [comment]
Sure, what exactly are u expecting after Abhinand's contribution?

**Comment by Vishruth-S** [comment]
@ArjunBhandari-666  Just some brief explanation of the various classifications in ML.
(Like given for topics in pat1 and part2)

**Comment by Vishruth-S** [comment]
@abhinand5  Are you still working on this? Can I get any update from you?

**Comment by abhinand5** [comment]
I've been quite busy with work over the past few days. Hopefully I'll send in a PR by this weekend

**Comment by Vishruth-S** [comment]
@abhinand5  I think you seem to be very busy, can I assign this issue to someone else in that case?

**Comment by Vishruth-S** [comment]
@abhinand5  Sorry but I am closing this due to lack of response.
