### ISSUE TITLE
Add documentation for Convolutional Neural Networks

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/Machine-Learning-with-Python#12]
It would be great if the concepts of Convolutional Neural Networks can be briefly explained.

Add your explanation in a file named `readme.md` inside `Part7 Deep Learning/Convolutional Neural Networks`

**Comment by pao0318** [comment]
I have made all the explaination . Will upload all the details of CNN if you are okay with this

**Comment by Vishruth-S** [comment]
Solved by #15 . Closing this.
