### ISSUE TITLE
Add documentation for Part4_Clustering

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/Machine-Learning-with-Python#2]
Currently, there is no explanation for concepts of clustering in ML (part4)
It would be nice if the 2 types of clustering can be briefly explained (similar to part1 and part2 concepts).

Add your explanation in a file named `readme.md` inside the respective folders.

**Comment by Shreerama9** [comment]
I'll be happy to take this one.
I just have to explain about Clustering and how you applied in your code.

**Comment by Shreerama9** [comment]
Can you assign me?

**Comment by Vishruth-S** [comment]
Sure @Shreerama9 You can take up this issue and work on it.
You just have to give a brief explanation of the 2 clustering methods. (explanation similar to those given in part1 and part2)

Add them in a file named `readme.md` inside their respective folders.

**Comment by Vishruth-S** [comment]
Solved by #8 . Closing this
