### ISSUE TITLE
Add Documentation for Part 6 - Natural Language Processing

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/Machine-Learning-with-Python#5]
Currently, there is no explanation for concepts of Natural Language Processing in ML (part6)
It would be nice if it can be briefly explained (similar to part1 and part2 concepts).

Add your explanation in a file named `readme.md`

**Comment by UsmanAhmadSaeed** [comment]
Hey, Can you assign this to me? I'd like to contribute.

**Comment by Vishruth-S** [comment]
Sure @UsmanAhmadSaeed  You can take it up and work on it 😃
