### ISSUE TITLE
Add documentation for Artificial Neural Networks

### ISSUE THREAD

**Issue by Vishruth-S** [Vishruth-S/Machine-Learning-with-Python#6]
It would be great if the concepts of Artificial Neural Networks can be briefly explained.

Add your explanation in a file named `readme.md` inside `Part7 Deep Learning/Artificial Neural Networks`

**Comment by Shreerama9** [comment]
Can you assign me.

**Comment by pao0318** [comment]
I have some good models of Neural Networks which can explain well about them.

**Comment by Vishruth-S** [comment]
@Shreerama9  Since you already got a chance, I think I'll give this to @pao0318 . Hope that's fine with you 😅 
So @pao0318 You can take up this issue 😄

**Comment by Shreerama9** [comment]
No Problem

It's fine

**Comment by Vishruth-S** [comment]
Solved by #11 . Closing this
